"""Exact route policy for Jarvis War Room Dashboard.

This list is intentionally exhaustive: new registered HTTP routes must update
this policy file and the matching security review. WebSocket routes are not
included because FastAPI exposes them without HTTP methods.
"""

EXPECTED_ROUTE_POLICY = (
    (('GET', 'HEAD'), '/api/plugins/jarvis-dashboard/docs'),
    (('GET',), '/api/plugins/jarvis-dashboard/health'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/admin/apply-migrations'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/admin/control-token-info'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/admin/generate-agent-files'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/admin/issue-control-token'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/admin/seed'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/agents/permanent-delete'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/agents/proposals'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/agents/propose'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/agents/remove'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/agents/removed'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/agents/restore'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/agents/skills'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/agents/skills'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/agents/{agent_id}/files'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/agents/{agent_id}/wake'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/agents/{agent_id}/wake-status'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/army/runs'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/army/runs'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/army/runs/{run_id}'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/army/runs/{run_id}/approve'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/army/runs/{run_id}/diff'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/army/runs/{run_id}/logs'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/army/runs/{run_id}/reject'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/army/runs/{run_id}/rerun'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/army/workers'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/audit'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/audit/stream'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/auth/session'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/budgets/analytics'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/chat'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/companies'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/companies/{company_id}/topology'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/dashboard/agents'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/dashboard/cache'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/dashboard/decisions'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/dashboard/kanban'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/dashboard/kanban/{project}'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/dashboard/memory'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/dashboard/metrics'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/dashboard/tasks'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/discord/threads'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/discord/webhook'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/edges'),
    (('DELETE',), '/api/plugins/jarvis-dashboard/v1/edges/{edge_id}'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/events'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/hires'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/hires'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/hires/{hire_id}/approve'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/hires/{hire_id}/reject'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/inbox'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/issues'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/issues'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/issues/{issue_id}/comments'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/kanban/task'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/kanban/tasks'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/block'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/comment'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/comments'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/complete'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/heartbeat'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/reassign'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/reclaim'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/runs'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/kanban/{task_id}/unblock'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/messages'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/messages/audit'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/messages/inbox'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/milestones'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/models'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/modes'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/nl-router'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/project/active'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/project/clone'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/project/list'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/project/select'),
    (('DELETE',), '/api/plugins/jarvis-dashboard/v1/project/{slug}'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/project/{slug}/context'),
    (('PATCH',), '/api/plugins/jarvis-dashboard/v1/project/{slug}/context'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/project/{slug}/decision'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/project/{slug}/decisions'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/project/{slug}/session'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/project/{slug}/sessions'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/projects'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/ready'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/roles'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/roles'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/roles/test'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/runs'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/runs/{run_id}/approve'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/runs/{run_id}/execute'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/runs/{run_id}/reject'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/sessions'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/sessions/{session_id}'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/skills'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/sse-session'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/workspace/clone'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/workspace/list'),
    (('POST',), '/api/plugins/jarvis-dashboard/v1/workspace/remove'),
    (('GET',), '/api/plugins/jarvis-dashboard/v1/workspace/status/{name}'),
    (('GET', 'HEAD'), '/docs/oauth2-redirect'),
    (('GET', 'HEAD'), '/openapi.json'),
)
