#!/usr/bin/env python3
"""gen_hermes_profiles.py — Generate Hermes profiles from a YAML spec.

Phase 1 of the Agentic Army sprint (D-2026-06-09). Reads `hermes_profiles.yaml`
and writes profile files (config.yaml + SOUL.md + AGENTS.md + HEARTBEAT.md +
TOOLS.md) for each entry.

CRITICAL SAFETY RULES (from codex review, 2026-06-09 02:00):

1. Default mode is **staging** — write to `state/proposals/profiles/<slug>/`,
   never to `~/.hermes/profiles/<slug>/`, unless the user passes --apply.
2. Never hardcode any path. All paths come from env vars or `Path.home()`.
3. Idempotent — if the target dir already exists, skip and log it.
4. writes_profile_configs is **false by default** for the API; the script
   itself is the *only* path that ever writes profile configs, and only on
   --apply.

Usage:
  # Stage all profiles (default — safe to run):
  python scripts/gen_hermes_profiles.py

  # Apply one profile to ~/.hermes/profiles/<slug>/:
  python scripts/gen_hermes_profiles.py --apply --slug jarvis-frontend

  # Apply all staged profiles:
  python scripts/gen_hermes_profiles.py --apply-all

  # Diff a staged profile against the live one:
  python scripts/gen_hermes_profiles.py --diff --slug jarvis-frontend
"""
from __future__ import annotations

import argparse
import difflib
import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

import yaml

log = logging.getLogger("gen_hermes_profiles")

# All paths come from env. Never hardcode.
HERMES_HOME = Path(
    os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))
).expanduser()
HERMES_PROFILES_DIR = Path(
    os.environ.get("HERMES_PROFILES_DIR", str(HERMES_HOME / "profiles"))
).expanduser()
STAGING_DIR = Path(
    os.environ.get(
        "JARVIS_PROFILE_STAGING_DIR",
        str(HERMES_HOME / "state" / "proposals" / "profiles"),
    )
).expanduser()
SPEC_PATH = Path(
    os.environ.get(
        "JARVIS_HERMES_PROFILES_SPEC",
        str(Path(__file__).parent / "hermes_profiles.yaml"),
    )
).expanduser()


# ── Safe-identifier validation (matches the rest of the dashboard) ──
import re

# Slug must start with lowercase, allow letters, digits, hyphen, underscore.
# Existing profiles are jarvis-<kebab> (e.g. jarvis-engineering-lead) but
# the user requested jarvis-ui_ux style too, so we accept both.
SAFE_SLUG = re.compile(r"^[a-z][a-z0-9_-]{0,63}$")


def _safe_slug(slug: str) -> str:
    if not SAFE_SLUG.match(slug):
        raise ValueError(
            f"slug {slug!r} is not a safe Hermes profile identifier "
            f"(must match {SAFE_SLUG.pattern})"
        )
    return slug


# ── Template renderers ────────────────────────────────────────────────

SOUL_TEMPLATE = """# {name}

> {role} profile in the {department} department. Auto-generated by
> `scripts/gen_hermes_profiles.py` (Agentic Army sprint, 2026-06-09).
> DO NOT edit this file directly — edit the YAML spec and re-run the
> generator. To customize, fork this file in-place (the generator
> skips profiles whose SOUL.md already exists).

{soul}

## Reports to
- `{reports_to}`

## Collaborates with
{collaborates_block}

## Default skills (seed)
The following Tier-1 skill repos are bound by default in
`state/skill_assignments/default.json`. Activate/deactivate per-project
in the dashboard.

{skills_block}

## Council membership
This profile is a member of the {team} team. It reports to
`{reports_to}` per the management protocol (`docs/MANAGEMENT_PROTOCOL.md`).
"""


AGENTS_TEMPLATE = """# AGENTS — {name}

> Auto-generated by `scripts/gen_hermes_profiles.py`. Re-run after
> editing the spec.

I am **{name}** (`{slug}`).
Department: {department}  |  Team: {team}  |  Model: {model}

## I report to
- `{reports_to}`

## I collaborate with
{collaborates_block}

## Default MCP servers
{mcp_block}
"""


HEARTBEAT_TEMPLATE = """# HEARTBEAT — {name}

> 7-step wake checklist for `{slug}`. Triggered manually or on the
> {department} team's heartbeat schedule (see Management Protocol).

1. **Load context.** Re-read this `HEARTBEAT.md`, your `SOUL.md`, and your `AGENTS.md`.
2. **Read open issues.** Walk the project board for items assigned to
   `{slug}` with state=open.
3. **Post a status comment** on the top issue: what you're doing + what
   you need.
4. **Check inbox.** Look for pending approvals, escalations, queries.
5. **Decide next action:**
   - If unblocked issue exists with priority in (high, urgent): emit TASK_ASSIGN.
   - If blocked: emit ESCALATION upward to `{reports_to}`.
6. **Emit message** through `acl.authorize_and_persist()`.
7. **Signal liveness + release wake_lock.**

## Forbidden during wake
- No shell exec outside the worktree.
- No autonomous hire without explicit Saiyudh approval.
"""


TOOLS_TEMPLATE = """# TOOLS — {name}

## Worker
- **worker_kind:** {worker_kind}
- **model:** {model}

## Allowed capabilities
- `task_read`, `task_write` (own tasks)
- `comment_post` (own + team-visible)
- `memory_read`, `memory_write` (own vault + shared)
- `message_send` (subject to authorize() ACL)
- `escalate_send` (vertical up)
- `liveness_ping`

## Forbidden
- `shell_exec` outside the worktree assigned to a run.
- `autonomous_hire` — no hire requests from this profile.
- Direct DB writes outside the spec 04 schema boundary.

## Default toolbelt
{tools_block}
"""


CONFIG_TEMPLATE = """name: {name}
slug: {slug}
# Model is a string for compatibility with the existing jarvis-* profiles
# (jarvis-boss, jarvis-engineering-lead). The roles.py and agent_growth.py
# code reads it as a string here. See the roles.py fix in the same PR.
model: {model}
role: {role}
worker_kind: {worker_kind}
department: {department}
team: {team}
reports_to: {reports_to}
collaborates_with:
{collaborates_yaml}
skills_seed:
{skills_seed_yaml}
mcp_servers:
{mcp_servers_yaml}
# This config.yaml is auto-generated by scripts/gen_hermes_profiles.py
# (Agentic Army sprint, 2026-06-09). The fields above extend the
# existing Hermes profile schema with department, team, reports_to,
# collaborators, skills_seed, and mcp_servers — all the fields the
# new SkillMarketplace dashboard panel needs.
"""


# ── Spec loader ───────────────────────────────────────────────────────

def load_spec(path: Path) -> List[Dict[str, Any]]:
    """Load the profile spec YAML. Returns a list of profile dicts."""
    if not path.exists():
        raise FileNotFoundError(f"spec not found: {path}")
    with path.open() as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict) or "profiles" not in data:
        raise ValueError(f"spec {path} must have a top-level 'profiles' key")
    profiles = data["profiles"]
    if not isinstance(profiles, list):
        raise ValueError(f"spec {path}: 'profiles' must be a list")
    for entry in profiles:
        if not isinstance(entry, dict):
            raise ValueError(f"spec {path}: each profile must be a dict")
        _safe_slug(entry["slug"])
        for required in ("name", "role", "department", "team", "model",
                         "worker_kind", "reports_to", "soul"):
            if required not in entry:
                raise ValueError(
                    f"spec {path}: profile {entry.get('slug')!r} missing {required!r}"
                )
    return profiles


# ── Renderers ─────────────────────────────────────────────────────────

def _format_bullets(items: List[str], empty_msg: str = "_(none)_") -> str:
    if not items:
        return empty_msg
    return "\n".join(f"- `{x}`" for x in items)


def _format_yaml_list(items: List[str]) -> str:
    """Format a list of strings as YAML list items, indented by 2 spaces."""
    if not items:
        return "  []  # (none)"
    return "\n".join(f"  - {item!r}" for item in items)


def render_profile_files(spec: Dict[str, Any]) -> Dict[str, str]:
    """Render the 5 files for a single profile. Returns {filename: content}."""
    slug = spec["slug"]
    name = spec["name"]
    role = spec["role"]
    department = spec["department"]
    team = spec["team"]
    model = spec["model"]
    worker_kind = spec["worker_kind"]
    reports_to = spec["reports_to"]
    collaborates = spec.get("collaborates_with", [])
    skills_seed = spec.get("skills_seed", [])
    mcp_servers = spec.get("mcp_servers", [])
    tools = spec.get("tools", [])
    soul = spec["soul"].strip()

    config_yaml = CONFIG_TEMPLATE.format(
        name=name, slug=slug, model=model, role=role, worker_kind=worker_kind,
        department=department, team=team, reports_to=reports_to,
        collaborates_yaml=_format_yaml_list(collaborates),
        skills_seed_yaml=_format_yaml_list(skills_seed),
        mcp_servers_yaml=_format_yaml_list(mcp_servers),
    )
    soul_md = SOUL_TEMPLATE.format(
        name=name, role=role, department=department, team=team,
        reports_to=reports_to,
        collaborates_block=_format_bullets(collaborates),
        skills_block=_format_bullets(skills_seed),
        soul=soul,
    )
    agents_md = AGENTS_TEMPLATE.format(
        name=name, slug=slug, department=department, team=team, model=model,
        reports_to=reports_to,
        collaborates_block=_format_bullets(collaborates),
        mcp_block=_format_bullets(mcp_servers),
    )
    heartbeat_md = HEARTBEAT_TEMPLATE.format(
        name=name, slug=slug, department=department, reports_to=reports_to,
    )
    tools_md = TOOLS_TEMPLATE.format(
        name=name, worker_kind=worker_kind, model=model,
        tools_block=_format_bullets(tools),
    )
    return {
        "config.yaml": config_yaml,
        "SOUL.md": soul_md,
        "AGENTS.md": agents_md,
        "HEARTBEAT.md": heartbeat_md,
        "TOOLS.md": tools_md,
    }


# ── Writer ────────────────────────────────────────────────────────────

def write_profile(spec: Dict[str, Any], target_dir: Path, *, overwrite: bool = False) -> Dict[str, str]:
    """Write a single profile to target_dir. Returns {filename: written_path}."""
    files = render_profile_files(spec)
    written: Dict[str, str] = {}
    target_dir.mkdir(parents=True, exist_ok=True)
    for filename, content in files.items():
        path = target_dir / filename
        if path.exists() and not overwrite:
            log.info("skip (exists): %s", path)
            continue
        path.write_text(content)
        written[filename] = str(path)
        log.info("wrote: %s", path)
    return written


def write_manifest(profiles: List[Dict[str, Any]], target_dir: Path) -> str:
    """Write a manifest.json next to the profiles so the apply step can verify."""
    manifest = {
        "version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/gen_hermes_profiles.py",
        "spec": str(SPEC_PATH),
        "count": len(profiles),
        "profiles": [
            {
                "slug": p["slug"],
                "name": p["name"],
                "role": p["role"],
                "department": p["department"],
                "team": p["team"],
                "model": p["model"],
                "worker_kind": p["worker_kind"],
                "reports_to": p["reports_to"],
                "collaborates_with": p.get("collaborates_with", []),
                "skills_seed": p.get("skills_seed", []),
                "mcp_servers": p.get("mcp_servers", []),
            }
            for p in profiles
        ],
    }
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True))
    return str(path)


# ── Diff helper ───────────────────────────────────────────────────────

def apply_staged(staging_dir: Path, live_dir: Path, slugs: List[str], *, overwrite: bool) -> Dict[str, List[str]]:
    """Copy staged files to live. The staged dir is the source of truth.

    Per codex review 2026-06-09: --apply must NOT re-render the YAML spec,
    it must copy the already-staged files. This guarantees the user is
    applying exactly what they reviewed.
    """
    written: Dict[str, List[str]] = {}
    for slug in slugs:
        src = staging_dir / slug
        if not src.is_dir():
            log.error("staged profile not found: %s", src)
            continue
        dst = live_dir / slug
        dst.mkdir(parents=True, exist_ok=True)
        files = [p for p in sorted(src.iterdir()) if p.is_file() and p.name != "manifest.json"]
        for f in files:
            target = dst / f.name
            if target.exists() and not overwrite:
                log.info("apply skip (exists): %s", target)
                continue
            target.write_text(f.read_text())
            written.setdefault(slug, []).append(str(target))
            log.info("applied: %s", target)
    return written


def diff_staging_vs_live(staging_dir: Path, live_dir: Path, slugs: List[str]) -> str:
    """Return a unified diff of staged files vs live. Staging is the source of truth."""
    lines: List[str] = []
    for slug in slugs:
        src_dir = staging_dir / slug
        if not src_dir.is_dir():
            lines.append(f"--- {slug}: no staged directory ---")
            continue
        dst_dir = live_dir / slug
        files = sorted({p.name for p in src_dir.iterdir() if p.is_file() and p.name != "manifest.json"})
        for fname in files:
            staged_content = (src_dir / fname).read_text() if (src_dir / fname).exists() else ""
            live_path = dst_dir / fname
            live_content = live_path.read_text() if live_path.exists() else ""
            if staged_content == live_content:
                continue
            diff = difflib.unified_diff(
                live_content.splitlines(keepends=True),
                staged_content.splitlines(keepends=True),
                fromfile=f"live/{slug}/{fname}",
                tofile=f"staged/{slug}/{fname}",
            )
            lines.extend(diff)
    return "".join(lines) if lines else "(no diff — staged == live)"


# ── CLI ───────────────────────────────────────────────────────────────

def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", default=str(SPEC_PATH), help="YAML spec path")
    parser.add_argument("--staging", default=str(STAGING_DIR), help="Staging dir")
    parser.add_argument("--live", default=str(HERMES_PROFILES_DIR), help="Live profiles dir")
    parser.add_argument("--slug", help="Process only this profile slug")
    parser.add_argument("--apply", action="store_true", help="Apply staged to live (DANGEROUS)")
    parser.add_argument("--apply-all", action="store_true", help="Apply all staged to live")
    parser.add_argument("--diff", action="store_true", help="Diff staged vs live")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing files")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

    spec_path = Path(args.spec).expanduser()
    staging_dir = Path(args.staging).expanduser()
    live_dir = Path(args.live).expanduser()

    profiles = load_spec(spec_path)
    if args.slug:
        profiles = [p for p in profiles if p["slug"] == args.slug]
        if not profiles:
            log.error("no profile found with slug %r in spec", args.slug)
            return 2

    if args.apply or args.apply_all:
        log.warning("APPLYING staged files to live: %s", live_dir)
        log.warning("This will mutate ~/.hermes/profiles/*/config.yaml.")
        slugs = [p["slug"] for p in profiles]
        written = apply_staged(staging_dir, live_dir, slugs, overwrite=args.overwrite)
        # Also drop a manifest at the live root
        manifest_src = staging_dir / "manifest.json"
        if manifest_src.exists():
            (live_dir / "manifest.json").write_text(manifest_src.read_text())
        log.warning("DONE. Applied %d profile(s) to %s", len(written), live_dir)
        return 0

    if args.diff:
        slugs = [p["slug"] for p in profiles]
        print(diff_staging_vs_live(staging_dir, live_dir, slugs))
        return 0

    # Default: stage to STAGING_DIR
    for spec in profiles:
        target = staging_dir / spec["slug"]
        write_profile(spec, target, overwrite=args.overwrite)
    write_manifest(profiles, staging_dir)
    log.info("STAGED %d profile(s) under %s", len(profiles), staging_dir)
    log.info("Review with: python scripts/gen_hermes_profiles.py --diff --slug <slug>")
    log.info("Apply with:  python scripts/gen_hermes_profiles.py --apply-all")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
